version: '2'
services:

  applications: # Applications Code Container (for volume sharing)
    image: tianon/true
    volumes:
      - /home/martin/Work:/var/www

  composer: # https://hub.docker.com/_/composer/
    image: x/composer
    build:
      context: ./composer

  php-fpm: # https://hub.docker.com/_/php/
    image: x/php-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile-71
    volumes_from:
      - applications
    expose:
      - "9000"
    environment:
      - NETTE_DEBUG=1

  nginx: # https://hub.docker.com/_/nginx/
    image: x/nginx
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - applications
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  mysql: # https://hub.docker.com/_/mysql/
    image: x/mysql
    build:
      context: ./mysql
      args:
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=mysql
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres: # https://hub.docker.com/_/postgres/
    image: x/postgres
    build: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
