version: '2'

services:

  applications: # Applications Code Container
    image: tianon/true
    volumes:
      - /home/martin/Work:/var/www

  php-fpm:
    image: x/php-fpm
    build:
      context: ./php-fpm
      args:
        - INSTALL_OPCACHE=true
      dockerfile: Dockerfile-71
    volumes_from:
      - applications
    expose:
      - "9000"
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:10.0.75.1"
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG=serverName=laravel
      - NETTE_DEBUG=1

  nginx:
    image: x/nginx
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - applications
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  mysql:
    image: x/mysql
    build:
      context: ./mysql
      args:
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=mysql
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres:
    image: x/postgres
    build: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
