version: '2'

services:

### Applications Code Container #############################

  applications:
    image: tianon/true
    volumes:
      - /home/martin/Work:/var/www

### Workspace Utilities Container ###########################

  workspace:
    build:
      context: ./workspace
      args:
        - INSTALL_NODE=true
        - INSTALL_YARN=true
        - COMPOSER_GLOBAL_INSTALL=true
        - PUID=1000
        - PGID=1000
        - NODE_VERSION=stable
        - YARN_VERSION=latest
        - TZ=Europe/Prague
    volumes_from:
      - applications
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:10.0.75.1"
    ports:
       - "2222:22"
#    tty: true # https://github.com/docker/compose/issues/3106

### PHP-FPM Container #######################################

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - INSTALL_XDEBUG=false
        - INSTALL_ZIP_ARCHIVE=false
        - INSTALL_OPCACHE=true
      dockerfile: Dockerfile-71
    volumes_from:
      - applications
    expose:
      - "9000"
    links:
      - workspace
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:10.0.75.1"
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG=serverName=laravel
      - NETTE_DEBUG=1

### Nginx Server Container ##################################

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - applications
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

### MySQL Container #########################################

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=mysql
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

### PostgreSQL Container ####################################

  postgres:
    build: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

### Volumes Setup ###########################################

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
  sessions: ## nothing is connected to this (- ./data/sessions:/sessions)
    driver: local
