FROM mysql:5.7

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

RUN chown -R mysql:root /var/lib/mysql/

ARG MYSQL_USER=mysql
ARG MYSQL_PASSWORD=mysql
ARG MYSQL_ROOT_PASSWORD=root

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

ADD my.cnf /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]

EXPOSE 3306
